// Injects structured data into every page, and FAQ sections into the six service
// pages. Idempotent: it replaces its own previous output rather than stacking, so
// it is safe to re-run after editing tools/seo-data.mjs.
//
//   node tools/build-seo.mjs
//
// Design notes
// ------------
// One @graph per page rather than several sibling <script> blocks. A graph lets
// each node reference the others by @id, so a crawler resolves "this Service is
// provided by that LocalBusiness, described on this WebPage, part of that
// WebSite" as one connected statement instead of four disconnected ones.
//
// The business node is emitted in full on the homepage only. Every other page
// carries a reference to its @id. Repeating the full node on eleven pages invites
// them to disagree with each other the moment one is edited.

import { readFileSync, writeFileSync } from 'node:fs';
import { ORIGIN, ID, BUSINESS, CITIES, SERVICES, FAQS } from './seo-data.mjs';

const START = '<!-- SEO:START — generated by tools/build-seo.mjs. Do not edit by hand. -->';
const END = '<!-- SEO:END -->';
const FAQ_START = '<!-- FAQ:START — generated by tools/build-seo.mjs. Do not edit by hand. -->';
const FAQ_END = '<!-- FAQ:END -->';

const esc = (s) =>
  String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

/* ------------------------------------------------------------------ nodes */

const postalAddress = {
  '@type': 'PostalAddress',
  streetAddress: BUSINESS.street,
  addressLocality: BUSINESS.city,
  addressRegion: BUSINESS.region,
  postalCode: BUSINESS.postal,
  addressCountry: BUSINESS.country,
};

// Named cities AND a radius. The cities match what a person types; the GeoCircle
// covers the towns between them that no one thought to list.
const areaServed = [
  ...CITIES.map((c) => ({ '@type': 'City', name: c.name, containedInPlace: { '@type': 'State', name: c.region } })),
  {
    '@type': 'GeoCircle',
    geoMidpoint: { '@type': 'GeoCoordinates', latitude: BUSINESS.lat, longitude: BUSINESS.lon },
    geoRadius: `${BUSINESS.radiusMiles * 1609}`, // metres
  },
];

function businessNode() {
  return {
    '@type': ['LocalBusiness', 'GeneralContractor'],
    '@id': ID.business,
    name: BUSINESS.name,
    legalName: BUSINESS.legalName,
    slogan: BUSINESS.slogan,
    description:
      'Land clearing, grading, brush clearing, storm debris removal, yard cleanup and small demolition across the CSRA — North Augusta and Aiken, South Carolina, and Augusta, Grovetown, Evans and Martinez, Georgia.',
    url: `${ORIGIN}/`,
    telephone: BUSINESS.phone,
    email: BUSINESS.email,
    priceRange: BUSINESS.priceRange,
    address: postalAddress,
    geo: { '@type': 'GeoCoordinates', latitude: BUSINESS.lat, longitude: BUSINESS.lon },
    hasMap: `https://www.google.com/maps?q=${encodeURIComponent(
      `${BUSINESS.street}, ${BUSINESS.city}, ${BUSINESS.region} ${BUSINESS.postal}`
    )}`,
    image: `${ORIGIN}/assets/img/og-image.jpg`,
    logo: `${ORIGIN}/assets/logo-m310.svg`,
    areaServed,
    // Duplicated as serviceArea because different consumers read one or the other.
    serviceArea: areaServed,
    openingHoursSpecification: [
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        opens: '00:00',
        closes: '23:59',
      },
    ],
    // Lets an assistant answer "what do they do?" without parsing prose.
    hasOfferCatalog: {
      '@type': 'OfferCatalog',
      name: 'Land clearing and site work services',
      itemListElement: SERVICES.map((s) => ({
        '@type': 'Offer',
        itemOffered: { '@type': 'Service', '@id': ID.service(s.slug), name: s.name, url: `${ORIGIN}/${s.slug}` },
      })),
    },
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: BUSINESS.phone,
      email: BUSINESS.email,
      contactType: 'sales',
      areaServed: ['US-SC', 'US-GA'],
      availableLanguage: 'English',
    },
  };
}

function websiteNode() {
  return {
    '@type': 'WebSite',
    '@id': ID.website,
    url: `${ORIGIN}/`,
    name: BUSINESS.name,
    publisher: { '@id': ID.business },
    inLanguage: 'en-US',
  };
}

function webPageNode({ path, title, description, primaryImage, type = 'WebPage', breadcrumbId }) {
  const node = {
    '@type': type,
    '@id': ID.page(path),
    url: `${ORIGIN}${path}`,
    name: title,
    description,
    isPartOf: { '@id': ID.website },
    about: { '@id': ID.business },
    inLanguage: 'en-US',
  };
  if (primaryImage) node.primaryImageOfPage = primaryImage;
  if (breadcrumbId) node.breadcrumb = { '@id': breadcrumbId };
  return node;
}

function breadcrumbNode(path, trail) {
  return {
    '@type': 'BreadcrumbList',
    '@id': `${ORIGIN}${path}#breadcrumb`,
    itemListElement: trail.map((step, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: step.name,
      item: `${ORIGIN}${step.path}`,
    })),
  };
}

function serviceNode(service) {
  return {
    '@type': 'Service',
    '@id': ID.service(service.slug),
    name: service.name,
    description: service.description,
    serviceType: service.name,
    url: `${ORIGIN}/${service.slug}`,
    provider: { '@id': ID.business },
    areaServed,
    // Points at the real conversion path, which is how these leads actually start.
    offers: {
      '@type': 'Offer',
      availability: 'https://schema.org/InStock',
      priceCurrency: 'USD',
      description: 'Free on-site estimate, no obligation.',
      url: `${ORIGIN}/contact`,
    },
  };
}

function faqNode(path, faqs) {
  return {
    '@type': 'FAQPage',
    '@id': `${ORIGIN}${path}#faq`,
    mainEntity: faqs.map((f) => ({
      '@type': 'Question',
      name: f.q,
      acceptedAnswer: { '@type': 'Answer', text: f.a },
    })),
  };
}

/* ------------------------------------------------------------------ pages */

const HOME = { path: '/', title: 'Land Clearing in North Augusta & Aiken | M310 Land Works' };

const PAGES = [
  {
    file: 'index.html',
    path: '/',
    type: 'WebPage',
    trail: null,
    extra: (p) => [businessNode(), websiteNode()],
  },
  { file: 'services.html', path: '/services', type: 'CollectionPage', trail: [HOME, { name: 'Services', path: '/services' }] },
  { file: 'about.html', path: '/about', type: 'AboutPage', trail: [HOME, { name: 'About', path: '/about' }] },
  { file: 'contact.html', path: '/contact', type: 'ContactPage', trail: [HOME, { name: 'Contact', path: '/contact' }] },
  { file: 'privacy.html', path: '/privacy', type: 'WebPage', trail: [HOME, { name: 'Privacy Policy', path: '/privacy' }] },
  ...SERVICES.map((s) => ({
    file: `${s.slug}.html`,
    path: `/${s.slug}`,
    type: 'WebPage',
    trail: [HOME, { name: 'Services', path: '/services' }, { name: s.label, path: `/${s.slug}` }],
    service: s,
  })),
];

/* --------------------------------------------------------------- rendering */

function faqSection(faqs) {
  const items = faqs
    .map(
      (f) => `          <details class="faq-item">
            <summary class="faq-q">${esc(f.q)}</summary>
            <div class="faq-a"><p>${esc(f.a)}</p></div>
          </details>`
    )
    .join('\n');

  return `${FAQ_START}
    <section class="py-14 md:py-20 bg-white" aria-labelledby="faq-heading">
      <div class="mx-auto max-w-4xl px-4 sm:px-6">
        <div class="rule-orange mb-4"></div>
        <h2 id="faq-heading" class="font-display text-3xl md:text-4xl uppercase mb-7">Common Questions</h2>
        <div class="space-y-3">
${items}
        </div>
        <p class="text-charcoal/70 mt-8">Still not sure? Call <a href="tel:${BUSINESS.phone}" class="text-orange-deep font-semibold" aria-label="Call M310 Land Works at 803-989-0031">(803) 989-0031</a> and ask — we answer seven days a week.</p>
      </div>
    </section>
    ${FAQ_END}`;
}

function replaceBlock(html, start, end, replacement) {
  const from = html.indexOf(start);
  if (from === -1) return null;
  const to = html.indexOf(end, from);
  if (to === -1) throw new Error(`found ${start} without its closing marker`);
  return html.slice(0, from) + replacement + html.slice(to + end.length);
}

let stats = { pages: 0, nodes: 0, faqPages: 0, faqs: 0 };

for (const page of PAGES) {
  let html = readFileSync(page.file, 'utf8');

  const title = (html.match(/<title>([^<]*)<\/title>/) || [])[1] || BUSINESS.name;
  const description = (html.match(/<meta name="description" content="([^"]*)"/) || [])[1] || '';
  const ogImage = (html.match(/<meta property="og:image" content="([^"]*)"/) || [])[1] || null;

  const graph = [];
  if (page.extra) graph.push(...page.extra(page));

  const breadcrumbId = page.trail ? `${ORIGIN}${page.path}#breadcrumb` : null;
  graph.push(
    webPageNode({
      path: page.path,
      title,
      description,
      primaryImage: ogImage,
      type: page.type,
      breadcrumbId,
    })
  );
  if (page.trail) graph.push(breadcrumbNode(page.path, page.trail));
  if (page.service) graph.push(serviceNode(page.service));

  const faqs = FAQS[page.service?.slug];
  if (faqs) graph.push(faqNode(page.path, faqs));

  // Non-home pages only reference the business; the full node lives on the home
  // page so there is exactly one authoritative copy to keep correct.
  if (!page.extra) graph.push({ '@type': 'LocalBusiness', '@id': ID.business, name: BUSINESS.name, url: `${ORIGIN}/` });

  const block = `${START}
  <script type="application/ld+json">
${JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 2)}
  </script>
  ${END}`;

  // Replace an existing generated block, or insert before </head>. The original
  // hand-written JSON-LD on the home page is removed the first time through.
  const replaced = replaceBlock(html, START, END, block);
  if (replaced) {
    html = replaced;
  } else {
    html = html.replace(
      /(\s*)<\/head>/,
      (_m, ws) => `${ws}${block}${ws}</head>`
    );
    // Drop the original hand-authored LocalBusiness block, now superseded.
    html = html.replace(
      /\s*<!-- JSON-LD LocalBusiness -->\s*<script type="application\/ld\+json">[\s\S]*?<\/script>/,
      ''
    );
  }

  if (faqs) {
    const section = faqSection(faqs);
    const swapped = replaceBlock(html, FAQ_START, FAQ_END, section);
    if (swapped) {
      html = swapped;
    } else {
      // Sits after the service copy and before the "Other Services" grid, so the
      // answers come before we send the reader elsewhere.
      const anchor = '    <section class="py-12 clay-band text-white text-center">';
      if (!html.includes(anchor)) throw new Error(`${page.file}: could not find the CTA band to insert the FAQ before`);
      html = html.replace(anchor, `${section}\n\n${anchor}`);
    }
    stats.faqPages++;
    stats.faqs += faqs.length;
  }

  writeFileSync(page.file, html);
  stats.pages++;
  stats.nodes += graph.length;
}

console.log(`pages processed:   ${stats.pages}`);
console.log(`schema nodes:      ${stats.nodes}`);
console.log(`FAQ sections:      ${stats.faqPages} (${stats.faqs} questions)`);
